# Generated by Django 3.0.6 on 2020-05-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=70)),
                ('mood', models.CharField(max_length=100)),
                ('floor', models.CharField(max_length=100)),
                ('toilet', models.CharField(choices=[('yes', '있음'), ('no', ' 없음')], max_length=3)),
                ('smoke', models.CharField(choices=[('yes', '있음'), ('no', ' 없음')], max_length=3)),
                ('elevator', models.CharField(choices=[('yes', '있음'), ('no', ' 없음')], max_length=3)),
                ('pet', models.CharField(choices=[('yes', '있음'), ('no', ' 없음')], max_length=4)),
                ('add', models.TextField()),
            ],
        ),
    ]
