# Generated by Django 3.0.6 on 2020-05-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='css',
            name='area',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='css',
            name='floor',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='css',
            name='mood',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='css',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
